In [2]:
# Hotel Pricing Lakehouse Project - Bronze Ingestion

import pandas as pd
from pathlib import Path
from datetime import datetime
import uuid

# Define paths
RAW_PATH = Path("C:\\Users\\cxpen\\Documents\\JOB\\Portfolios\\hotel-pricing-lakehouse\\data\\raw\\hotel_bookings.csv")
BRONZE_DIR = Path("C:\\Users\\cxpen\\Documents\\JOB\\Portfolios\\hotel-pricing-lakehouse\\data\\bronze")
BRONZE_DIR.mkdir(parents=True, exist_ok=True)

# Read raw data
df_raw = pd.read_csv(RAW_PATH)

# Add technical metadata
batch_id = str(uuid.uuid4())

df_bronze = df_raw.copy()
df_bronze["ingestion_timestamp"] = datetime.now()
df_bronze["source_file_name"] = RAW_PATH.name
df_bronze["batch_id"] = batch_id

# Save Bronze data
BRONZE_PATH = BRONZE_DIR / "hotel_bookings_bronze.csv"
df_bronze.to_csv(BRONZE_PATH, index=False)

print("Bronze ingestion completed.")
print(f"Rows ingested: {len(df_bronze)}")
print(f"Columns: {len(df_bronze.columns)}")
print(f"Batch ID: {batch_id}")
print(f"Bronze file saved to: {BRONZE_PATH}")

Bronze ingestion completed.
Rows ingested: 119390
Columns: 35
Batch ID: 4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
Bronze file saved to: C:\Users\cxpen\Documents\JOB\Portfolios\hotel-pricing-lakehouse\data\bronze\hotel_bookings_bronze.csv

In [3]:
df_bronze.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,ingestion_timestamp,source_file_name,batch_id
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,Transient,98.0,0,1,Check-Out,2015-07-03,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5

In [4]:
df_bronze[["ingestion_timestamp", "source_file_name", "batch_id"]].head()

,ingestion_timestamp,source_file_name,batch_id
0,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
1,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
2,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
3,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5
4,2026-05-16 10:44:39.377975,hotel_bookings.csv,4f7e4a36-3ea5-4840-9c9c-9422ea391bd5